// <auto-generated />
using System;
using ClientNexus.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace ClientNexus.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ClientNexusSchema")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientNexus.Domain.Entities.AccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels", "ClientNexusSchema");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Super Admin"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Customer Service"
                        });
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Address", b =>
                {
                    b.Property<int>("BaseUserId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("DetailedAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MapUrl")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BaseUserId", "Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Content.DCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DCategories", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Content.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Documents", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Content.DocumentCategory", b =>
                {
                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("DCategoryId")
                        .HasColumnType("int");

                    b.HasKey("DocumentId", "DCategoryId");

                    b.HasIndex("DCategoryId");

                    b.ToTable("DocumentCategories", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Content.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes", "ClientNexusSchema");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Article"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Template"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.ToTable("Cities", "ClientNexusSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "مدينة نصر",
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "الهرم",
                            StateId = 2
                        });
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries", "ClientNexusSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "EG",
                            Name = "مصر"
                        });
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.OfficeImageUrl", b =>
                {
                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ServiceProviderId", "Id");

                    b.ToTable("OfficeImageUrls", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States", "ClientNexusSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CA",
                            CountryId = 1,
                            Name = "القاهرة"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GZ",
                            CountryId = 1,
                            Name = "الجيزة"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "ALX",
                            CountryId = 1,
                            Name = "الاسكندرية"
                        });
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.ToTable("Payments", "ClientNexusSchema");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.PhoneNumber", b =>
                {
                    b.Property<int>("BaseUserId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("BaseUserId", "Id");

                    b.ToTable("PhoneNumbers", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<int?>("SolvingAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("SolvingAdminId");

                    b.ToTable("Problems", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.AppointmentCost", b =>
                {
                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("AppointmentType")
                        .HasColumnType("char(1)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ServiceProviderId", "AppointmentType");

                    b.ToTable("AppointmentCosts", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.CaseFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultCaseId")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultCaseId");

                    b.ToTable("CaseFiles", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.ClientServiceProviderFeedback", b =>
                {
                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.HasKey("ServiceProviderId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientServiceProviderFeedbacks", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.EmergencyCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ServiceProviderTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderTypeId");

                    b.ToTable("EmergencyCategories", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("Services", "ClientNexusSchema");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId", "Date")
                        .IsUnique();

                    b.ToTable("Slots", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.BaseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("BlockedById")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NotificationToken")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.HasIndex("BlockedById");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("BaseUsers", "ClientNexusSchema");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.ServiceProviderSpecialization", b =>
                {
                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("ServiceProviderId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("ServiceProviderSpecializations", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.ServiceProviderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ServiceProviderTypes", "ClientNexusSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lawyer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Doctor"
                        });
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ServiceProviderTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderTypeId");

                    b.ToTable("Specializations", "ClientNexusSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "جنائى",
                            ServiceProviderTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "مدنى",
                            ServiceProviderTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "اسرة",
                            ServiceProviderTypeId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "ClientNexusSchema");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "ClientNexusSchema");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "ClientNexusSchema");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "ClientNexusSchema");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "ClientNexusSchema");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.ServicePayment", b =>
                {
                    b.HasBaseType("ClientNexus.Domain.Entities.Payment");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasIndex("ServiceId")
                        .IsUnique()
                        .HasFilter("[ServiceId] IS NOT NULL");

                    b.ToTable("ServicePayments", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.SubscriptionPayment", b =>
                {
                    b.HasBaseType("ClientNexus.Domain.Entities.Payment");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("SubscriptionPayments", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.Appointment", b =>
                {
                    b.HasBaseType("ClientNexus.Domain.Entities.Services.Service");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancellationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReminderSentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.HasIndex("SlotId");

                    b.ToTable("Appointments", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.ConsultationCase", b =>
                {
                    b.HasBaseType("ClientNexus.Domain.Entities.Services.Service");

                    b.ToTable("ConsultationCases", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.EmergencyCase", b =>
                {
                    b.HasBaseType("ClientNexus.Domain.Entities.Services.Service");

                    b.Property<Point>("MeetingLocation")
                        .HasColumnType("geography");

                    b.Property<int?>("TimeForArrival")
                        .HasColumnType("int");

                    b.ToTable("EmergencyCases", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.Question", b =>
                {
                    b.HasBaseType("ClientNexus.Domain.Entities.Services.Service");

                    b.Property<string>("AnswerBody")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsAnswerHelpful")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool?>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.ToTable("Questions", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.Admin", b =>
                {
                    b.HasBaseType("ClientNexus.Domain.Entities.Users.BaseUser");

                    b.Property<int>("AccessLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("ApprovedById");

                    b.ToTable("Admins", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.Client", b =>
                {
                    b.HasBaseType("ClientNexus.Domain.Entities.Users.BaseUser");

                    b.Property<float>("Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.ToTable("Clients", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.ServiceProvider", b =>
                {
                    b.HasBaseType("ClientNexus.Domain.Entities.Users.BaseUser");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<Point>("CurrentLocation")
                        .HasColumnType("geography");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageIDUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageNationalIDUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsAvailableForEmergency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLocationUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainImage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<float>("Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("SubscriptionExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("TypeId");

                    b.ToTable("ServiceProviders", "ClientNexusSchema");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Address", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.BaseUser", "BaseUser")
                        .WithMany("Addresses")
                        .HasForeignKey("BaseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Others.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUser");

                    b.Navigation("City");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Content.Document", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Content.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Users.Admin", "UploadedBy")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Content.DocumentCategory", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Content.DCategory", "Category")
                        .WithMany("DocumentCategories")
                        .HasForeignKey("DCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Content.Document", "Document")
                        .WithMany("DocumentCategories")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.City", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Others.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Others.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.OfficeImageUrl", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.ServiceProvider", "ServiceProvider")
                        .WithMany("OfficeImageUrls")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.State", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Others.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.PhoneNumber", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.BaseUser", "BaseUser")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("BaseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseUser");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Problem", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.Client", "Client")
                        .WithMany("Problems")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Services.Service", "Service")
                        .WithOne("Problem")
                        .HasForeignKey("ClientNexus.Domain.Entities.Problem", "ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Users.ServiceProvider", "ServiceProvider")
                        .WithMany("Problems")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Users.Admin", "SolvingAdmin")
                        .WithMany("AssignedProblems")
                        .HasForeignKey("SolvingAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("ServiceProvider");

                    b.Navigation("SolvingAdmin");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.AppointmentCost", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.ServiceProvider", "ServiceProvider")
                        .WithMany("AppointmentCosts")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.CaseFile", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Services.ConsultationCase", "ConsultCase")
                        .WithMany("CaseFiles")
                        .HasForeignKey("ConsultCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultCase");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.ClientServiceProviderFeedback", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.Client", "Client")
                        .WithMany("ClientServiceProviderFeedbacks")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Users.ServiceProvider", "ServiceProvider")
                        .WithMany("ClientServiceProviderFeedbacks")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.EmergencyCategory", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.ServiceProviderType", "ServiceProviderType")
                        .WithMany("EmergencyCategories")
                        .HasForeignKey("ServiceProviderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProviderType");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.Service", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.Client", "Client")
                        .WithMany("RequestedServices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Users.ServiceProvider", "ServiceProvider")
                        .WithMany("ServicesProvided")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.Slot", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.ServiceProvider", "ServiceProvider")
                        .WithMany("Slots")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.BaseUser", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.Admin", "BlockedBy")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("BlockedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BlockedBy");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.ServiceProviderSpecialization", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.ServiceProvider", "ServiceProvider")
                        .WithMany("ServiceProviderSpecializations")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Users.Specialization", "Specialization")
                        .WithMany("ServiceProviderSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.Specialization", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.ServiceProviderType", "ServiceProviderType")
                        .WithMany("Specializations")
                        .HasForeignKey("ServiceProviderTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceProviderType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Users.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.ServicePayment", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Payment", null)
                        .WithOne()
                        .HasForeignKey("ClientNexus.Domain.Entities.Others.ServicePayment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Services.Service", "Service")
                        .WithOne("ServicePayment")
                        .HasForeignKey("ClientNexus.Domain.Entities.Others.ServicePayment", "ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.SubscriptionPayment", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Payment", null)
                        .WithOne()
                        .HasForeignKey("ClientNexus.Domain.Entities.Others.SubscriptionPayment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Users.ServiceProvider", "ServiceProvider")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.Appointment", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Services.Service", null)
                        .WithOne()
                        .HasForeignKey("ClientNexus.Domain.Entities.Services.Appointment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Services.Slot", "Slot")
                        .WithMany("Appointments")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.ConsultationCase", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Services.Service", null)
                        .WithOne()
                        .HasForeignKey("ClientNexus.Domain.Entities.Services.ConsultationCase", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.EmergencyCase", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Services.Service", null)
                        .WithOne()
                        .HasForeignKey("ClientNexus.Domain.Entities.Services.EmergencyCase", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.Question", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Services.Service", null)
                        .WithOne()
                        .HasForeignKey("ClientNexus.Domain.Entities.Services.Question", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.Admin", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.AccessLevel", "AccessLevel")
                        .WithMany("Admins")
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Users.Admin", "ApprovingAdmin")
                        .WithMany("ApprovedAdmins")
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClientNexus.Domain.Entities.Users.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("ClientNexus.Domain.Entities.Users.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLevel");

                    b.Navigation("ApprovingAdmin");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.Client", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("ClientNexus.Domain.Entities.Users.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.ServiceProvider", b =>
                {
                    b.HasOne("ClientNexus.Domain.Entities.Users.Admin", "ApprovingAdmin")
                        .WithMany("ApprovedServiceProviders")
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClientNexus.Domain.Entities.Users.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("ClientNexus.Domain.Entities.Users.ServiceProvider", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientNexus.Domain.Entities.Users.ServiceProviderType", "Type")
                        .WithMany("ServiceProviders")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovingAdmin");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.AccessLevel", b =>
                {
                    b.Navigation("Admins");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Content.DCategory", b =>
                {
                    b.Navigation("DocumentCategories");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Content.Document", b =>
                {
                    b.Navigation("DocumentCategories");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Content.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("States");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Others.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.Service", b =>
                {
                    b.Navigation("Problem");

                    b.Navigation("ServicePayment");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.Slot", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.BaseUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.ServiceProviderType", b =>
                {
                    b.Navigation("EmergencyCategories");

                    b.Navigation("ServiceProviders");

                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.Specialization", b =>
                {
                    b.Navigation("ServiceProviderSpecializations");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Services.ConsultationCase", b =>
                {
                    b.Navigation("CaseFiles");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.Admin", b =>
                {
                    b.Navigation("ApprovedAdmins");

                    b.Navigation("ApprovedServiceProviders");

                    b.Navigation("AssignedProblems");

                    b.Navigation("BlockedUsers");

                    b.Navigation("UploadedDocuments");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.Client", b =>
                {
                    b.Navigation("ClientServiceProviderFeedbacks");

                    b.Navigation("Problems");

                    b.Navigation("RequestedServices");
                });

            modelBuilder.Entity("ClientNexus.Domain.Entities.Users.ServiceProvider", b =>
                {
                    b.Navigation("AppointmentCosts");

                    b.Navigation("ClientServiceProviderFeedbacks");

                    b.Navigation("OfficeImageUrls");

                    b.Navigation("Problems");

                    b.Navigation("ServiceProviderSpecializations");

                    b.Navigation("ServicesProvided");

                    b.Navigation("Slots");

                    b.Navigation("SubscriptionPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
